<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Slightpay\Payment\Block\Branding\Product */

$active = $block->getActive();
$branding = $block->getBranding();


if ($active && $branding && $block->getItemsCount()) {
    // phpcs:ignore Magento2.Security.LanguageConstruct.DirectOutput
    echo ('<div style="display: flex;flex-wrap:wrap;align-items:center;justify-content: flex-end;margin-bottom:15px;">o págalo en <div style="color: #1a4bcd;margin: 0 4px;">4 pagos</div> con <img src="https://slightpay.s3.us-west-2.amazonaws.com/logo-slightpay-blanco.svg" style="width: 90px;margin: 0 8px; filter: invert(1);"/><div style="color: #1a4bcd; cursor: pointer; text-decoration: underline #1a4bcd" id="click-header"><a href="#" id="click-header">Conoce más.</a></div></div>');
    echo $block->getChildHtml('with-items');
    echo ('<style type="text/css">.modal-inner-wrap{ width: 520px !important; } .img-slightpay { width: 520px; } .container-img-slightpay { width: 520px; } .modal-header{position: absolute !important;right: 5px!important; } .modal-content { padding: 0 !important ;} @media (max-width: 1200px) { .modal-inner-wrap { width: 450px !important; } .container-img-slightpay { width: 450px !important; } .img-slightpay { width: 450px !important; } } @media (max-width: 690px) { .modal-inner-wrap { width: 400px !important; height: 660px !important; } .container-img-slightpay { width: 400px !important; } .img-slightpay { width: 400px !important; } } @media (max-width: 500px) { .modal-inner-wrap { width: 360px !important; height: 592px !important; } .container-img-slightpay { width: 360px !important; } .img-slightpay { width: 360px !important; } .modal-popup.modal-slide { left: 0px !important; } }</style>');
    echo ('<div id="header-modal" class="container-img-slightpay" style="display:none;"><img class="img-slightpay" src="https://slightpay.s3-us-west-2.amazonaws.com/slightpay_branding.png" /></div>');
    echo ('<script>require(["jquery","Magento_Ui/js/modal/modal"],function($,modal) {var options = {type: "popup",responsive: true,title: "",buttons: []}; var popup = modal(options, $("#header-modal"));$("#click-header").on("click",function(){ $("#header-modal").modal("openModal");});});</script>');
} else {
    // phpcs:ignore Magento2.Security.LanguageConstruct.DirectOutput
    echo $block->getChildHtml('no-items');
}
