<?php
/**
 * @var $block \slightpay\payment\Block\Form\SlightpayButton
 */
$methodCode = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset items <?= /* @noEscape */ $methodCode ?>" id="payment_form_<?= /* @noEscape */ $methodCode ?>" style="display: none">
    <div class="field number required">
    </div>
</fieldset>

<script type="text/javascript">
    require(['jquery', 'module'], function($, myscript) {
        myscript();
    });
</script>